### ISSUE TITLE
Invalid target

### ISSUE THREAD

**Issue by ritesh-pandey** [lalwanivikas/window-game#1]
![bug](https://cloud.githubusercontent.com/assets/1433681/5651806/c7afca5c-96d0-11e4-88b0-17d0c1875035.png)
I tried playing on Safari. The window cannot be resized beyond a certain level. The target I am given cannot be achieved.
I was unable to reduce width of window any further.
See attached image.

**Comment by lalwanivikas** [comment]
Thanks for reporting. I've fixed it. Please let me know if it works fine for you now. Thanks :)
